### ISSUE TITLE
Old "Aired Today" Playlists not being removed.

### ISSUE THREAD

**Issue by leftovernick** [cfurrow/plex-playlist-creators#4]
The issue is in the check for playlists starting with "Aired Today" but not being today's playlist, it will always return false.

Currently the check is as follows:
`if playlist.title == TODAY_PLAY_TITLE.startswith('Aired Today') and not TODAY_PLAY_TITLE:`

The `not TODAY_PLAY_TITLE` will always return `false` since the `TODAY_PLAY_TITLE` is being checked if it is a boolean of false (which it never will be). Instead it should check whether the `playlist.title` is equal to `TODAY_PLAY_TITLE`. When using and, it will not carry over what you were comparing in the first statement. They are independent from each other. so `a > 1 and not 3`will always return false, but `a > 1 and not a == 3`will return true on numbers above 1 and not equal to 3.

there's a similar issue in the first statement where we're checking if `playlist.title` is equal to the boolean result of `TODAY_PLAY_TITLE.startswith('Aired Today')` which will be either true or false.

Here is the fix below as I can not open a PR:

`if playlist.title.startswith('Aired Today') and not playlist.title == TODAY_PLAY_TITLE:`

**Comment by leftovernick** [comment]
There is also an issue with the delete request. It is requesting to delete TODAY_PLAY_TITLE

currently its trying this:

```
r = requests.delete('{}/playlists/{}?X-Plex-Token={}'
                    .format(baseurl, TODAY_PLAY_TITLE, token))
        print('Removing old Aired Today Playlists ')
        print(r)
```

It's passing the string of TODAY_PLAY_TITLE which it should never be doing. What we need to do is pass the key for the playlist that was flagged as an old playlist with `playlist.key.split('/playlists/')[1]` We should also validate the response code

So the whole thing should look like this:

```
r = requests.delete('{}/playlists/{}?X-Plex-Token={}'.format(baseurl, playlist.key.split('/playlists/')[1], token))
    if r.status_code == 204:
      print('Removing old Aired Today Playlists ')
    else:
      print('Failed to remove old Aired Today Playlist ')
    print(r)
```

**Comment by cfurrow** [comment]
Thanks, @leftovernick -- would you be able to create a PR for your intended fixes? I can review that and merge it that way.

Take care!

**Comment by cfurrow** [comment]
Thanks again for the issue, and fixes. I re-read your initial message and saw that you were not able to create a PR--I missed that on my first read. You should have been able to fork this, create a PR on your forked repo, and that would then open a PR on my repo... Unless I messed up a setting somewhere.

Regardless, I integrated your fixes into the main branch: https://github.com/cfurrow/plex-playlist-creators/commit/95bd62c720514f779a2e1b75a1e2978a91db7406

I also added an improvement to not automatically delete old "aired today" playlists unless the user specifies the `--delete` argument. I don't recall my original reason for deleting old playlists, as these scripts are a few years old, and I only recently added to github so others could possibly get benefit out of them.

```sh
# deletes old playlists and creates one for 12-30
python aired_today_playlist.py --delete '2023-12-30'

# does not delete old playlists and creates one for 12-30
python aired_today_playlist.py '2023-12-30'
```

**Comment by cfurrow** [comment]
Fixed as part of https://github.com/cfurrow/plex-playlist-creators/commit/95bd62c720514f779a2e1b75a1e2978a91db7406

**Comment by cfurrow** [comment]
Fixed as part of https://github.com/cfurrow/plex-playlist-creators/commit/95bd62c720514f779a2e1b75a1e2978a91db7406
